# Generated by Django 4.2.10 on 2025-05-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('nc_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='vessel_id',
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='vessel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='core.vessel'),
            preserve_default=False,
        ),
    ]
