# Generated by Django 4.2.10 on 2025-04-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nc_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(upload_to='evidence_files/'),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='detection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='reference_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='source_type',
            field=models.CharField(choices=[('INSPECTION', 'Inspection'), ('AUDIT', 'Audit'), ('COMPLAINT', 'Complaint'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preventiveaction',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_preventive_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preventiveaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='NCHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_ADDED', 'Attachment Added')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('non_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nc_module.nonconformity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NCComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('non_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nc_module.nonconformity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NCAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='nc_attachments/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('non_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='nc_module.nonconformity')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_nc_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
