# Generated by Django 4.2.10 on 2025-05-09 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('vessel_compliance', 'Vessel Compliance'), ('maintenance_status', 'Maintenance Status'), ('certification', 'Certification Status'), ('fuel_consumption', 'Fuel Consumption'), ('crew_roster', 'Crew Roster'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('query_parameters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters_used', models.JSONField(default=dict)),
                ('result_data', models.JSONField()),
                ('file_format', models.CharField(default='json', max_length=10)),
                ('file_location', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessel_reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('time_of_day', models.TimeField()),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=10)),
                ('recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessel_reporting.report')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('count', 'Count'), ('percentage', 'Percentage'), ('average', 'Average'), ('sum', 'Sum'), ('min', 'Minimum'), ('max', 'Maximum')], max_length=20)),
                ('data_source', models.CharField(max_length=100)),
                ('query_definition', models.JSONField(default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_interval_minutes', models.IntegerField(default=60)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
