# Generated by Django 4.2.10 on 2025-04-30 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('CAPTAIN', 'Captain'), ('CHIEF_OFFICER', 'Chief Officer'), ('SECOND_OFFICER', 'Second Officer'), ('THIRD_OFFICER', 'Third Officer'), ('CHIEF_ENGINEER', 'Chief Engineer'), ('SECOND_ENGINEER', 'Second Engineer'), ('THIRD_ENGINEER', 'Third Engineer'), ('ELECTRICIAN', 'Electrician'), ('BOSUN', 'Bosun'), ('ABLE_SEAMAN', 'Able Seaman'), ('COOK', 'Cook'), ('STEWARD', 'Steward'), ('OILER', 'Oiler')], max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('seaman_book_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('medical_information', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrewCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('COC', 'Certificate of Competency'), ('COE', 'Certificate of Endorsement'), ('STCW', 'STCW Certificate'), ('MEDICAL', 'Medical Certificate'), ('SAFETY', 'Safety Training Certificate'), ('SECURITY', 'Security Training Certificate'), ('OTHER', 'Other Certificate')], max_length=20)),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=100)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='crew_certificates/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='crew.crew')),
            ],
            options={
                'unique_together': {('crew', 'certificate_type', 'certificate_number')},
            },
        ),
        migrations.CreateModel(
            name='CertificateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('days_before_expiry', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Notification Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15)),
                ('message', models.TextField()),
                ('sent_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crew.crewcertificate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(choices=[('CAPTAIN', 'Captain'), ('CHIEF_OFFICER', 'Chief Officer'), ('SECOND_OFFICER', 'Second Officer'), ('THIRD_OFFICER', 'Third Officer'), ('CHIEF_ENGINEER', 'Chief Engineer'), ('SECOND_ENGINEER', 'Second Engineer'), ('THIRD_ENGINEER', 'Third Engineer'), ('ELECTRICIAN', 'Electrician'), ('BOSUN', 'Bosun'), ('ABLE_SEAMAN', 'Able Seaman'), ('COOK', 'Cook'), ('STEWARD', 'Steward'), ('OILER', 'Oiler')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crew.crew')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='crew.vessel')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('crew', 'vessel', 'start_date')},
            },
        ),
    ]
