# Generated by Django 4.2.10 on 2025-05-01 18:37

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE crew_certificatenotification 
            ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
            ALTER TABLE crew_certificatenotification 
            DROP COLUMN IF EXISTS created_at,
            DROP COLUMN IF EXISTS updated_at;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE crew_certificatenotification 
            ADD COLUMN IF NOT EXISTS created_by_id INTEGER,
            ADD COLUMN IF NOT EXISTS updated_by_id INTEGER,
            ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by_id) REFERENCES authentication_user(id) ON DELETE SET NULL,
            ADD CONSTRAINT fk_updated_by FOREIGN KEY (updated_by_id) REFERENCES authentication_user(id) ON DELETE SET NULL;
            """,
            reverse_sql="""
            ALTER TABLE crew_certificatenotification 
            DROP CONSTRAINT IF EXISTS fk_created_by,
            DROP CONSTRAINT IF EXISTS fk_updated_by,
            DROP COLUMN IF EXISTS created_by_id,
            DROP COLUMN IF EXISTS updated_by_id;
            """
        ),
    ]
