# Generated by Django 4.2.10 on 2025-05-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('certificates', '0002_alter_certificate_vessel'),
        ('crew', '0002_auto_20250501_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewassignment',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='core.vessel'),
        ),
        migrations.DeleteModel(
            name='Vessel',
        ),
    ]
