# Generated by Django 4.2.10 on 2025-04-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ism_compliance.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISMRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ism_section', models.CharField(choices=[('1', '1 - General'), ('2', '2 - Safety and Environmental Protection Policy'), ('3', '3 - Company Responsibilities and Authority'), ('4', '4 - Designated Person(s)'), ('5', "5 - Master's Responsibility and Authority"), ('6', '6 - Resources and Personnel'), ('7', '7 - Development of Plans for Shipboard Operations'), ('8', '8 - Emergency Preparedness'), ('9', '9 - Reports and Analysis of Non-conformities, Accidents and Hazardous Occurrences'), ('10', '10 - Maintenance of the Ship and Equipment'), ('11', '11 - Documentation'), ('12', '12 - Company Verification, Review and Evaluation'), ('13', '13 - Certification, Verification and Control'), ('14', '14 - Interim Certification'), ('15', '15 - Verification'), ('16', '16 - Forms of Certificates')], max_length=3)),
                ('requirement_code', models.CharField(help_text="ISM code reference (e.g., '1.4.2')", max_length=20)),
                ('requirement_text', models.TextField()),
                ('guidance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ism_section', 'requirement_code'],
                'indexes': [models.Index(fields=['ism_section'], name='ism_complia_ism_sec_7cad2b_idx'), models.Index(fields=['requirement_code'], name='ism_complia_require_8e8228_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='core.vessel')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable'), ('pending_review', 'Pending Review')], default='pending_review', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_items', to=settings.AUTH_USER_MODEL)),
                ('ism_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='ism_compliance.ismrequirement')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photograph'), ('record', 'Record'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=ism_compliance.models.evidence_file_path)),
                ('reference_url', models.URLField(blank=True, help_text='URL reference to evidence in external system', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('compliance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ism_compliance.complianceitem')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_review_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ism_compliance.complianceitem')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['scheduled_date'], name='ism_complia_schedul_6e0628_idx'), models.Index(fields=['status'], name='ism_complia_status_92a29f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complianceitem',
            index=models.Index(fields=['vessel'], name='ism_complia_vessel_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceitem',
            index=models.Index(fields=['compliance_status'], name='ism_complia_complia_b0bfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceitem',
            index=models.Index(fields=['assessment_date'], name='ism_complia_assessm_cc1b3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceitem',
            constraint=models.UniqueConstraint(
                fields=('ism_requirement', 'vessel'),
                name='unique_requirement_vessel'
            ),
        ),
    ]
