# Generated by Django 4.2.10 on 2025-05-09 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('faulty', 'Faulty'), ('decommissioned', 'Decommissioned')], default='operational', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.vessel')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('interval_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('running_hours', 'Running Hours'), ('custom_days', 'Custom Days')], max_length=20)),
                ('interval_value', models.PositiveIntegerField(help_text='Value for interval (days or hours)')),
                ('last_completed_date', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('responsible_role', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vessel_pms.equipment')),
            ],
            options={
                'verbose_name': 'Maintenance Task',
                'verbose_name_plural': 'Maintenance Tasks',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('running_hours', models.PositiveIntegerField(blank=True, help_text='Equipment running hours at time of maintenance', null=True)),
                ('parts_used', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='vessel_pms.equipment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vessel_pms.maintenancetask')),
            ],
            options={
                'verbose_name': 'Maintenance History',
                'verbose_name_plural': 'Maintenance History',
                'ordering': ['-completed_date'],
            },
        ),
    ]
