# Generated by Django 4.2.10 on 2025-05-09 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('PROCEDURE', 'Procedure'), ('CHECKLIST', 'Checklist'), ('MANUAL', 'Manual'), ('FORM', 'Form'), ('POLICY', 'Policy')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='procedures/%Y/%m/')),
                ('version', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('CURRENT', 'Current'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('IN_REVIEW', 'In Review'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('review_interval_months', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('previous_procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='safety_procedures.procedure')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='safety_procedures.procedure')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('changes_required', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='safety_procedures.procedure')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='safety_procedures.procedurecategory')),
            ],
            options={
                'verbose_name_plural': 'Procedure Categories',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='safety_procedures.procedurecategory'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProcedureAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_version', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='safety_procedures.procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_date'],
                'unique_together': {('procedure', 'user', 'acknowledged_version')},
            },
        ),
    ]
