# Generated by Django 4.2.10 on 2025-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_vessel'),
        ('certificates', '0003_migrate_vessel_data'),
    ]

    operations = [
    ]
